# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0002_auto_20161021_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelbuddy.Users'),
        ),
    ]
