# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0003_trips_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='join',
            managers=[
                ('joinsMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
